# Generated by Django 4.0.3 on 2022-04-25 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bankingSolutuon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('pin1', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email1', models.CharField(max_length=122)),
                ('pin1', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='ChangePin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=122)),
                ('old_pin', models.CharField(max_length=122)),
                ('new_pin1', models.CharField(max_length=122)),
                ('new_pin2', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=122)),
                ('pin1', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='Lock2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=122)),
                ('pin1', models.CharField(max_length=122)),
                ('pin2', models.CharField(max_length=122)),
            ],
        ),
        migrations.RenameField(
            model_name='sendmoney',
            old_name='pass1',
            new_name='Bank',
        ),
        migrations.AddField(
            model_name='mobilerecharge',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendmoney',
            name='note',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forget_password_token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
